### ISSUE TITLE
Add an if/else statement

### ISSUE THREAD

**Issue by mcheng09** [emiliogomezlavin/buzzing-fiesta#2]
Even when no one buzzes in, when you press submit, it answers for the 2nd player. Add an if/else statement so that if it's submitted without anyone buzzing in, it has a message that says "no one has buzzed in yet!" or something like that.

**Comment by emiliogomezlavin** [comment]
Bug fixed. When submit button is clicked and no player buzzed, a message is shown letting the players know and requesting them to play a new song.
